# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1htxdPyUG00UTdiN82F-skSuPaISEkBqOiZSwX2WPUXk/edit#gid=0"

# From your JSON key file
[google_service_account]
type = "service_account"
project_id = "big-depth-391213"
private_key_id = "d51be79b897a7a333ecec2a957e10093abf58116"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDeunOO+bgM9Zbe
x70G42ZLSKpyPLHNVEXOqM/xIwoYPCVTMY1QZGmdhGtK95V/0ZTxeK9X1rO3jAaZ
2FlSVFcZQOGImqR56PnzRxZemK2Z1+b4cnRhLjWClpqENAzJWnrpGD9jM2WzKPsl
UQ18G201hoVcTa7yJhSl5yl7Q19sF7KI8zHBTOVUO80mOyZ9f9MAjffO0jDeRulD
lfk4anNwRwwIWLXh4AGtgIeRwzWu+HUlCAP/dfPXOVDNSmVSLeT5AAAj7kaaMLd0
eVOwDNdrP+jmpJxwka1FrCymLOlRjYrMGAlsP8YI6//U2iZZ3aQhs8nhJwV4Z9aA
IefkrnJnAgMBAAECggEACTGMDJDyj8JhZbURReQEDcPO7qPiY6CAuHzlBxs+/Zdv
TlBOI3fe7iwQRl9oMdxOTWtXCC//ahT4aXLx45aXTnO2+4MFRVegXZzdElmIrOrU
XgP8xCLP/aHGzgHcrJZfWsNv9mHMPF7K2Gml6K4JziWigpgISnbXmljWMFWBw6iL
qgOlmaYpsaTl+6ZlnznBcOG0rnb0mlduKx707BAUJ8PsHdtBYwsRuzHmltA/ZUlK
slpeDCQcZS9EanAMjv2A7S3rb96gCq92ZGZzWrt/mT1AQImvygE4b5hncGu9J1qz
31GOzO31iyZXHkEbRT7jA8sgdkf6FYtSyqmQ4nN3YQKBgQD/Fve1pq6dqJJBI7wi
8HYtngFXXMcIG0E8urPSHhJq7q8G4Zs843BsId9WtkVwI6DCDVdootA1q8AA67Tu
jZynQYrp3xxCi+4GNuWke7J6LKRMc57y80HXEHWQtkr3CXJwQxhotXKKWgbrnvzz
weCLgi/LF84tbEPbW6MrubyBoQKBgQDfheuvlphZQleM74yZgJLJPPdB18seCkMv
WF8s89wCx6Wgg3Y0yDL6EZpNkwBkyzvxJI3SmHz/5YImmfsh6MJE7EsXE89b1KTa
CmkjYbJLgoGKVMbTbPiK8bURbPStROLan7OUDNSqGDuw1gaxMjH4xw8hRgBPoYNK
75eurkuHBwKBgBu/itiWth3uTWKKmZePYruZmXnAXOIz3MfXY2Iy5Tv+lMmB1xor
f3ozwRC0qR8GsSEKxHxcYZvFABDZkwf0HZtQFOVV4MQYZp8Eb7yRvBtwKbsrRJoW
/g1/+9nvCn6O54Twt4IEYt5L5r7Qv6FgcKWcVsiX4VStl0AQWtKR1MChAoGAEIxl
qpZHqTQUL0b87dBrDaMJ20ISs6Km3rZ4NWfIfhwx0vRop/e6bnEnL18WxF+XjH7c
UR8hAgEH5bu4sAX/fALSfF7nFzFjExF6PzhYbua2mHs2TSjgLck/Uo7yfnF/Khhw
vyFEDWPF542w6SWCNZznLdt04nBevAmI/VHCHbkCgYBXq0Bb5pzFUzFbNvU0OF9J
ih29DcFgX7evKzsMjPrlQjR4WgtBkwerbD5n+YF+KBCw/TFzA/ob0QOmp3+VlZIZ
KacK9LOKvb1yYB68IVF8oh2h2jlF5jjNojuplkgc8/4VF4d0eLj5ZAHZRI0Ii055
NlxYst/1dc2QfntP4+33xw==
-----END PRIVATE KEY-----"""
client_email = "test-gs@big-depth-391213.iam.gserviceaccount.com"
client_id = "101170581427661035112"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/test-gs%40big-depth-391213.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

