# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1htxdPyUG00UTdiN82F-skSuPaISEkBqOiZSwX2WPUXk/edit#gid=0"

# From your JSON key file
[google_service_account]
type = "service_account"
project_id = "big-depth-391213"
private_key_id = "07d0b12390139dd46148301eca7a48e4264c583e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDDaoyOiTyLWd9M
uRbJz4KfgiqxjanZbpygV0JX+w/w9ng8ro12bXBHQpcEgs5ncsvwVJJcEHGdVaLZ
C1DI2glzXQKC0/chvtjHjCpFiviRPMHM0NF6QN/rZMy+m2y23LafXafshFcWhUkt
xxgQ3FpHt7G0RXaHmGE1/6qJVx5D8lJqZBCSi/L122OiFjujcPwiXg1TDUyQp0+h
SEIqXXwlmVhiEcpiNOTV5Oy3gLF2uI6uQrz2uMoS5l7rgfGRgcC2qaFG+Y6NHlRv
OZawOo/XbGYx2VZY6S4vcan2EeVzEtIYE/rj00kXU6oMZqKlagRG8AixBGVPngOY
9dDTDrcZAgMBAAECggEAHWM35ZSaZAt9MxTPqkRYbMP+xypafW4uxEczHTeOr2pl
bRzD/egZ30GSo/VG9JQ1OryBMTKw31waTCExQi9WBgEaCFI3o13HzISV89ThKjhU
nchWhFfexM/pIY4OpJZfKWrEfuNtFGAxf96lzh1RP2FO6mEa4OvnzJ7ZBuPw039J
ZdSzeysEEudYIM7YCTvCZe+y4a50MO70FqHbkogAdvd5M/SYtOi3vImMqAtRpjcE
C3STUjstI+QmD7UNg0eYYhVjxizA/ONTDTESmNp7tGLcYHeOiB2z54N2yP+BR4L+
t8+CSxOOYLpF5bKFFAvSDZBCnGXlH4ubPkET/rhPzQKBgQDzX/FuhaftjI1vY+If
COx7A2Bk44mWHi+0R2pII96wBmn3i2JkoWBmlzOIDdVFaydqHxG24iUzL+8anM2O
/KTasJMqOdolVQr52CgV9I6md8LBfvQ6w7V4cU0b/Zn1CcT/KtVvN1ndPZx6vmgQ
pGoLQrg/3fFEhpXRPLDF2FAl7QKBgQDNjbVSR2y7jETAcGMrPquAf8N1vHMFUNHa
9fhIoK3ZwLrP/h0J9WRMV0VDFosLy4xOBa2rSM4gbwvdsRMEpFP4AAdQAM2wv+iZ
4i1stWIxptGQ7G48EPB2AHJT+FgWQYrpEZcJ5T7ybKaDJS1m6qu4pCfHj4VZ57i9
OYbWN5awXQKBgCWS3G1ZyTFNj9BwtUphUFE1lj49OtKoWmkU1X3Ju+mlM9r58/jh
SUbNdTE+IX0ULAOgRFXd2Cxs7BdJuhqnOrRgqnfMcrdsx8MG8jlhhlyBBNpmxUIF
UREFPQhjQM+p8HYMoOMIwqD7kBsLJnnbSFvwsw15MHSJ6rthCVGiMc2JAoGBAMJK
Ycsly/byPMIQ+QuVLxJEsYIF4Epz/AgVWtt7VRhv/aQ/sz8IfgdSrhsdocxCV5of
7+no5Tzu+a5Qg4NtuBjAHilWuRWKL9fUW89XGzuHTKrJb+DCuicvgOEx6kEPLrfi
cntd/sOyQynO6D1RL4NVVmxgklFKn+nsCDFPVdXZAoGBAOFOQLwvp7D2zEhcAdmx
6EjjqcvRYAxSroXeCRDGMJkgYrVIVTiRcE8Zdu6RAZD+ErE/X1HG+kHZwdK4igWu
jt3p5Ey+yvqYKpU/1IIMSMaOKnIy9XxiYt2KlSLvGW9jXG1HHZcyPTEFEIqn0ays
JMcnz/2taITh1DCZLPROc+D8
-----END PRIVATE KEY-----"""
client_email = "elios-418@big-depth-391213.iam.gserviceaccount.com"
client_id = "102102433765656250260"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/elios-418%40big-depth-391213.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

